#!/bin/sh

set -e

COOKBOOKS_PATH="cookbooks"

# Bootstrap if required
test -x bin/rspec && test -d "$COOKBOOKS_PATH" || script/bootstrap

# Run RSpec tests
exec bin/rspec $RSPEC_OPTS "$COOKBOOKS_PATH"
